#!/bin/bash 
#PBS -l nodes=1:ppn=16
#PBS -l walltime=1:0:00
#PBS -N nscf 
#PBS -V
#PBS -q mpi

bindir=/shared/ESPRESSO/espresso-6.2.0/bin

input=input.inp
output=output.dat

mpirun -machinefile $PBS_NODEFILE -np $NPROCS $bindir/pw.x < $input > $output


